// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://robertai.fr/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://robertai.fr/support",
            "email": "support@robertai.fr"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Logs in a user using email/password or token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login form",
                        "name": "loginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authHandler.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token and user details",
                        "schema": {
                            "$ref": "#/definitions/authHandler.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/authHandler.LoginError400"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/authHandler.LoginError403"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logs out the user by revoking their token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authHandler.LogoutResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/authHandler.LogoutError401"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Get details of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get user details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authHandler.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/authHandler.MeError"
                        }
                    }
                }
            },
            "post": {
                "description": "Update details of the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update user details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User update data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authHandler.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authHandler.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/authHandler.MeError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/authHandler.MeError"
                        }
                    }
                }
            }
        },
        "/auth/recover": {
            "post": {
                "description": "Generates a recovery token for the user to reset their password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Account Recovery",
                "parameters": [
                    {
                        "description": "Account recovery form",
                        "name": "askRecoverForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authHandler.AskRecoverForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/authHandler.RecoverResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/authHandler.RecoverError400"
                        }
                    }
                }
            }
        },
        "/auth/reset_password": {
            "post": {
                "description": "Reset the password for a user using a recovery token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Reset user password",
                "parameters": [
                    {
                        "description": "Password Reset Form",
                        "name": "passwordResetForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authHandler.PasswordResetForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/authHandler.PasswordResetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/authHandler.PasswordResetError400"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/authHandler.PasswordResetError403"
                        }
                    }
                }
            }
        },
        "/auth/signout": {
            "post": {
                "description": "Sign out the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign out user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Signout form",
                        "name": "signoutForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignoutForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignoutError400"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignoutError403"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Signup a new user",
                "parameters": [
                    {
                        "description": "Signup form",
                        "name": "signupForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignupForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignupError400"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/authHandler.SignupError409"
                        }
                    }
                }
            }
        },
        "/chat/mail": {
            "post": {
                "description": "Analyze a mail and return a response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Mail analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Chat page form",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatMailForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatMailResponse"
                        }
                    }
                }
            }
        },
        "/chat/page/analyze": {
            "post": {
                "description": "Analyze a page content and return a response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Page analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Chat page form",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatPageForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatPageResponse"
                        }
                    }
                }
            }
        },
        "/chat/page/resume": {
            "post": {
                "description": "Analyze a page content and return a summary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Page resume",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Chat page form",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatPageForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatPageResponse"
                        }
                    }
                }
            }
        },
        "/chat/query": {
            "post": {
                "description": "Handle a chat query and return a response with optional session context",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Chat query form",
                        "name": "query",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatQueryForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/chatHandler.ChatQueryResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions": {
            "get": {
                "description": "Retrieve all chat sessions for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get all chat sessions for the authenticated user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of chat sessions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chat.ChatSession"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new chat session with an initial message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Create a new chat session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create session form",
                        "name": "createSessionForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatHandler.CreateSessionForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Session created successfully",
                        "schema": {
                            "$ref": "#/definitions/chatHandler.CreateSessionResponse"
                        }
                    },
                    "400": {
                        "description": "First message is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/chat/sessions/{sessionId}": {
            "delete": {
                "description": "Delete a specific chat session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Delete a chat session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/chat/sessions/{sessionId}/messages": {
            "get": {
                "description": "Retrieve all messages for a specific chat session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get messages for a specific chat session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of chat messages",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chat.ChatMessage"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a message to a specific chat session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Create a new chat session message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "sessionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session token",
                        "name": "Robert-Connect-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Add message form",
                        "name": "addMessageForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chatHandler.AddMessageForm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message added successfully",
                        "schema": {
                            "$ref": "#/definitions/chatHandler.AddMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID or missing fields",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Session not found or access denied",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "authHandler.AskRecoverForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "authHandler.LoginError400": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Please fully fill in the login form"
                }
            }
        },
        "authHandler.LoginError403": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid email or password"
                }
            }
        },
        "authHandler.LoginForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "authHandler.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string"
                        },
                        "firstname": {
                            "type": "string"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "lastname": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "authHandler.LogoutError401": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid session"
                }
            }
        },
        "authHandler.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Logged out successfully"
                }
            }
        },
        "authHandler.MeError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Incorrect token"
                }
            }
        },
        "authHandler.PasswordResetError400": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Please fully fill in the password reset form"
                }
            }
        },
        "authHandler.PasswordResetError403": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid recover token"
                }
            }
        },
        "authHandler.PasswordResetForm": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "authHandler.PasswordResetResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Password reset successfully"
                }
            }
        },
        "authHandler.RecoverError400": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Please fully fill in the account recovery form"
                }
            }
        },
        "authHandler.RecoverResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Recovery token created successfully"
                }
            }
        },
        "authHandler.SignoutError400": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Empty password"
                }
            }
        },
        "authHandler.SignoutError403": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid password"
                }
            }
        },
        "authHandler.SignoutForm": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "authHandler.SignoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Signout successful"
                }
            }
        },
        "authHandler.SignupError400": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Please fully fill in the signup form"
                }
            }
        },
        "authHandler.SignupError409": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Email not available"
                }
            }
        },
        "authHandler.SignupForm": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "firstname": {
                    "type": "string",
                    "example": "John"
                },
                "lastname": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "example": "Password123!"
                }
            }
        },
        "authHandler.SignupResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Signup successful"
                }
            }
        },
        "authHandler.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                }
            }
        },
        "authHandler.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                }
            }
        },
        "chat.ChatMessage": {
            "type": "object",
            "properties": {
                "bot_response": {
                    "type": "string"
                },
                "chat_session_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "user_message": {
                    "type": "string"
                }
            }
        },
        "chat.ChatSession": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "chatHandler.AddMessageForm": {
            "type": "object",
            "properties": {
                "bot_response": {
                    "type": "string"
                },
                "user_message": {
                    "type": "string"
                }
            }
        },
        "chatHandler.AddMessageResponse": {
            "type": "object",
            "properties": {
                "message_id": {
                    "type": "integer"
                }
            }
        },
        "chatHandler.ChatMailForm": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                }
            }
        },
        "chatHandler.ChatMailResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "chatHandler.ChatPageForm": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "chatHandler.ChatPageResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "chatHandler.ChatQueryForm": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "session_id": {
                    "type": "integer"
                }
            }
        },
        "chatHandler.ChatQueryResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "chatHandler.CreateSessionForm": {
            "type": "object",
            "properties": {
                "first_message": {
                    "type": "string"
                }
            }
        },
        "chatHandler.CreateSessionResponse": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Robert AI API",
	Description:      "This is the Robert AI API documentation.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
